#include<iostream>

int main()
{
    int x; // Declaration of integer variable x
    x = 5; // Assignment of value 5 to variable x
    int y = 6; // Declaration and initialization of integer variable y with value 6

    // Print the value of x followed by a newline
    std::cout << x << '\n';

    // Print the value of y followed by a newline
    std::cout << y << '\n';

    return 0;
}


